const PedidoStatus = Object({
  AGUARDANDO_PAGAMENTO: "AGUARDANDO PAGAMENTO",
  PENDENTE: "PENDENTE",
  COZINHA: "COZINHA",
  PRONTO: "PRONTO",
  ENTREGUE: "ENTREGUE",
  CANCELADO: "CANCELADO",
});

export default PedidoStatus;
